AWSTemplateFormatVersion: '2010-09-09'

Resources:
  BucketForLambdaZips:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: The name of the created S3 bucket
    Value: !Ref BucketForLambdaZips
